<a href="https://colab.research.google.com/github/AbduFakir/Python-DataScience/blob/main/analyst_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.Series([5,7,8,8,12,None,"8 "])
df

0       5
1       7
2       8
3       8
4      12
5    None
6      8
dtype: object

In [4]:
#Remove the trailing spaces in the data.
df = df.astype(str).str.strip()
df

0       5
1       7
2       8
3       8
4      12
5    None
6       8
dtype: object

In [5]:
#make the sting to numeric

df = pd.to_numeric(df,errors='coerce')
df

0     5.0
1     7.0
2     8.0
3     8.0
4    12.0
5     NaN
6     8.0
dtype: float64

In [8]:
print(df.isnull())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [6]:
#Null imputation

median = df.median()

df = df.fillna(median)
df

0     5.0
1     7.0
2     8.0
3     8.0
4    12.0
5     8.0
6     8.0
dtype: float64

In [11]:
#Finding Outliers

Q1 = np.percentile(df,25)
Q3 = np.percentile(df,75)

print(Q1)
print(Q3)

7.5
8.0

In [14]:
IQR = Q3 - Q1
print(IQR)

0.5

In [16]:
upper_bound = Q3 + 1.5*IQR
lower_bound = Q1 - 1.5*IQR
print(upper_bound)
print(lower_bound)

8.75
6.75

In [17]:
outliers = df[(df<lower_bound)|(df>upper_bound)]
print(outliers)

0     5.0
4    12.0
dtype: float64